## Text Preprocessing

### Lowercasing

In [ ]:
import pandas as pd

df = pd.read_csv("lowercasing.txt")
df.head()

Empty DataFrame
Columns: [Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.]
Index: []

In [ ]:
df.iloc[:, 0] = df.iloc[:, 0].str.lower()

Empty DataFrame
Columns: [Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.]
Index: []

In [ ]:
df = pd.read_csv("IMDB Dataset.csv")

# df.head()
df.loc[5, "review"] = df.loc[5, "review"].lower() # Lowercasing single data point
df.loc[:, "review"] = df.loc[:, "review"].str.lower() # Lowercasing all data points in a column

# df["review"] = df["review"].str.lower() # Lowercasing all data points in a column

df["review"][112]

"it's terrific when a funny movie doesn't make smile you. what a pity!! this film is very boring and so long. it's simply painfull. the story is staggering without goal and no fun.<br /><br />you feel better when it's finished."

### Remove HTML Tag

In [ ]:
# making a function to remove html tags

import regex as re
def remove_HTML_tags(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r'', text)

text = df['review'][3]
#text = "<br>This is a HTML tag</br>"
remove_HTML_tags(text)

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [ ]:
# To remove html tags from each data points in an entire column

# df['review'] = df['review'].apply(remove_HTML_tags)

for x in df['review']:
    remove_HTML_tags(x)

df['review'][71]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

### Remove URL's

In [43]:
import regex as re

def remove_urls(text):
    pattern = re.compile(r"https?://\S+|www\.\S+")
    return pattern.sub(r'', text).strip()

text1 = "Check out my instagram https://www.instagram.com/imsohamofc/qwerty"
remove_urls(text1)
text2 = "Check out my instagram http://www.instagram.com/imsohamofc/qwerty"
remove_urls(text2)
text3 = "Check out my instagram www.instagram.com/imsohamofc/qwerty"
remove_urls(text3)
text4 = "Check out my instagram https://www.instagram.com/imsohamofc/qwerty and also my facebook www.facebook.com/imsohamofc/qwerty"
remove_urls(text4)

'Check out my instagram  and also my facebook'

### Removing Punctuation

In [ ]:
import string, time

exclude = string.punctuation

# Method 1
# def remove_punctuation(text):
#     for char in exclude:
#         text = text.replace(char, '')
#     return text

# Method 2 This method is much faster than the previous one
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', exclude))

text = "Hello, my name is Soham Mirashi. How do you do?"

remove_punctuation(text)

'Hello my name is Soham Mirashi How do you do'

### Chat word treatment

In [47]:
slang_dict = {}

with open("slang.txt", "r") as f:
    for line in f:
        line = line.strip()
        
        if "=" in line:
            key, value = line.split("=", 1)
            slang_dict[key.lower()] = value.lower()

print(slang_dict)

{'a3': 'anytime, anywhere, anyplace', 'adih': 'another day in hell', 'afk': 'away from keyboard', 'afaik': 'as far as i know', 'asap': 'as soon as possible', 'asl': 'age, sex, location', 'atk': 'at the keyboard', 'atm': 'at the moment', 'bae': 'before anyone else', 'bak': 'back at keyboard', 'bbl': 'be back later', 'bbs': 'be back soon', 'bfn': 'bye for now', 'b4n': 'bye for now', 'brb': 'be right back', 'bruh': 'bro', 'brt': 'be right there', 'bsaaw': 'big smile and a wink', 'btw': 'by the way', 'bwl': 'bursting with laughter', 'csl': 'canâ€™t stop laughing', 'cu': 'see you', 'cul8r': 'see you later', 'cya': 'see you', 'dm': 'direct message', 'faq': 'frequently asked questions', 'fc': 'fingers crossed', 'fimh': 'forever in my heart', 'fomo': 'fear of missing out', 'fr': 'for real', 'fwiw': "for what it's worth", 'fyp': 'for you page', 'fyi': 'for your information', 'g9': 'genius', 'gal': 'get a life', 'gg': 'good game', 'gmta': 'great minds think alike', 'gn': 'good night', 'goat': 'greatest of all time', 'gr8': 'great!', 'hbd': 'happy birthday', 'ic': 'i see', 'icq': 'i seek you', 'idc': 'i donâ€™t care', 'idk': "i don't know", 'ifyp': 'i feel your pain', 'ilu': 'i love you', 'ily': 'i love you', 'imho': 'in my honest/humble opinion', 'imu': 'i miss you', 'imo': 'in my opinion', 'iow': 'in other words', 'irl': 'in real life', 'iykyk': 'if you know, you know', 'jk': 'just kidding', 'kiss': 'keep it simple, stupid', 'l': 'loss', 'l8r': 'later', 'ldr': 'long distance relationship', 'lmk': 'let me know', 'lmao': 'laughing my a** off', 'lol': 'laughing out loud', 'ltns': 'long time no see', 'm8': 'mate', 'mfw': 'my face when', 'mid': 'mediocre', 'mrw': 'my reaction when', 'mte': 'my thoughts exactly', 'nvm': 'never mind', 'nrn': 'no reply necessary', 'npc': 'non-player character', 'oic': 'oh i see', 'op': 'overpowered', 'pita': 'pain in the a**', 'pov': 'point of view', 'prt': 'party', 'prw': 'parents are watching', 'rofl': 'rolling on the floor laughing', 'roflol': 'rolling on the floor laughing out loud', 'rotflmao': 'rolling on the floor laughing my a** off', 'rn': 'right now', 'sk8': 'skate', 'stats': 'your sex and age', 'sus': 'suspicious', 'tbh': 'to be honest', 'tfw': 'that feeling when', 'thx': 'thank you', 'time': 'tears in my eyes', 'tldr': 'too long, didnâ€™t read', 'tntl': 'trying not to laugh', 'ttfn': 'ta-ta for now!', 'ttyl': 'talk to you later', 'u': 'you', 'u2': 'you too', 'u4e': 'yours for ever', 'w': 'win', 'w8': 'wait...', 'wb': 'welcome back', 'wtf': 'what the f**k', 'wtg': 'way to go!', 'wuf': 'where are you from?', 'wyd': 'what you doing?', 'wywh': 'wish you were here', 'zzz': 'sleeping, bored, tired'}

In [53]:
def slang_conversion(text):
    words = text.split()
    return " ".join([slang_dict.get(word.lower(), word) for word in words])

slang_conversion("LOL that was sick!!")
slang_conversion("LO that was sick!!")
slang_conversion("FYI New Delhi is the capital of India")

'for your information New Delhi is the capital of India'

### Spelling Correction

In [60]:
from textblob import TextBlob

incorrect_text = "Theree arre certsin elemnts that are radeo activ lke uranium"

textblb = TextBlob(incorrect_text)
textblb.correct().string

'There are certain elements that are radio active like cranium'

### Removing stop words

In [ ]:
# words like a, the, are etc. does not add a lot of significance in the meaning of the scentence
# There are few cases where you keep the stop words like POS

from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]